// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	IdempotencyKey  *idempotencyKey
	Order           *order
	OrderItem       *orderItem
	Permission      *permission
	Product         *product
	RefreshToken    *refreshToken
	Role            *role
	RolePermission  *rolePermission
	Session         *session
	StockAdjustment *stockAdjustment
	User            *user
	UserRole        *userRole
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	IdempotencyKey = &Q.IdempotencyKey
	Order = &Q.Order
	OrderItem = &Q.OrderItem
	Permission = &Q.Permission
	Product = &Q.Product
	RefreshToken = &Q.RefreshToken
	Role = &Q.Role
	RolePermission = &Q.RolePermission
	Session = &Q.Session
	StockAdjustment = &Q.StockAdjustment
	User = &Q.User
	UserRole = &Q.UserRole
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		IdempotencyKey:  newIdempotencyKey(db, opts...),
		Order:           newOrder(db, opts...),
		OrderItem:       newOrderItem(db, opts...),
		Permission:      newPermission(db, opts...),
		Product:         newProduct(db, opts...),
		RefreshToken:    newRefreshToken(db, opts...),
		Role:            newRole(db, opts...),
		RolePermission:  newRolePermission(db, opts...),
		Session:         newSession(db, opts...),
		StockAdjustment: newStockAdjustment(db, opts...),
		User:            newUser(db, opts...),
		UserRole:        newUserRole(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	IdempotencyKey  idempotencyKey
	Order           order
	OrderItem       orderItem
	Permission      permission
	Product         product
	RefreshToken    refreshToken
	Role            role
	RolePermission  rolePermission
	Session         session
	StockAdjustment stockAdjustment
	User            user
	UserRole        userRole
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) UnderlyingDB() *gorm.DB { return q.db }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		IdempotencyKey:  q.IdempotencyKey.clone(db),
		Order:           q.Order.clone(db),
		OrderItem:       q.OrderItem.clone(db),
		Permission:      q.Permission.clone(db),
		Product:         q.Product.clone(db),
		RefreshToken:    q.RefreshToken.clone(db),
		Role:            q.Role.clone(db),
		RolePermission:  q.RolePermission.clone(db),
		Session:         q.Session.clone(db),
		StockAdjustment: q.StockAdjustment.clone(db),
		User:            q.User.clone(db),
		UserRole:        q.UserRole.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.clone(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		IdempotencyKey:  q.IdempotencyKey.replaceDB(db),
		Order:           q.Order.replaceDB(db),
		OrderItem:       q.OrderItem.replaceDB(db),
		Permission:      q.Permission.replaceDB(db),
		Product:         q.Product.replaceDB(db),
		RefreshToken:    q.RefreshToken.replaceDB(db),
		Role:            q.Role.replaceDB(db),
		RolePermission:  q.RolePermission.replaceDB(db),
		Session:         q.Session.replaceDB(db),
		StockAdjustment: q.StockAdjustment.replaceDB(db),
		User:            q.User.replaceDB(db),
		UserRole:        q.UserRole.replaceDB(db),
	}
}

type queryCtx struct {
	IdempotencyKey  IIdempotencyKeyDo
	Order           IOrderDo
	OrderItem       IOrderItemDo
	Permission      IPermissionDo
	Product         IProductDo
	RefreshToken    IRefreshTokenDo
	Role            IRoleDo
	RolePermission  IRolePermissionDo
	Session         ISessionDo
	StockAdjustment IStockAdjustmentDo
	User            IUserDo
	UserRole        IUserRoleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		IdempotencyKey:  q.IdempotencyKey.WithContext(ctx),
		Order:           q.Order.WithContext(ctx),
		OrderItem:       q.OrderItem.WithContext(ctx),
		Permission:      q.Permission.WithContext(ctx),
		Product:         q.Product.WithContext(ctx),
		RefreshToken:    q.RefreshToken.WithContext(ctx),
		Role:            q.Role.WithContext(ctx),
		RolePermission:  q.RolePermission.WithContext(ctx),
		Session:         q.Session.WithContext(ctx),
		StockAdjustment: q.StockAdjustment.WithContext(ctx),
		User:            q.User.WithContext(ctx),
		UserRole:        q.UserRole.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
