// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"clean-arch-gin/mysqlstore/model"
)

func newIdempotencyKey(db *gorm.DB, opts ...gen.DOOption) idempotencyKey {
	_idempotencyKey := idempotencyKey{}

	_idempotencyKey.idempotencyKeyDo.UseDB(db, opts...)
	_idempotencyKey.idempotencyKeyDo.UseModel(&model.IdempotencyKey{})

	tableName := _idempotencyKey.idempotencyKeyDo.TableName()
	_idempotencyKey.ALL = field.NewAsterisk(tableName)
	_idempotencyKey.ID = field.NewUint64(tableName, "id")
	_idempotencyKey.UserID = field.NewUint64(tableName, "user_id")
	_idempotencyKey.Operation = field.NewString(tableName, "operation")
	_idempotencyKey.IdempotencyKey = field.NewString(tableName, "idempotency_key")
	_idempotencyKey.RequestHash = field.NewBytes(tableName, "request_hash")
	_idempotencyKey.OrderID = field.NewUint64(tableName, "order_id")
	_idempotencyKey.CreatedAt = field.NewTime(tableName, "created_at")
	_idempotencyKey.UpdatedAt = field.NewTime(tableName, "updated_at")

	_idempotencyKey.fillFieldMap()

	return _idempotencyKey
}

type idempotencyKey struct {
	idempotencyKeyDo idempotencyKeyDo

	ALL            field.Asterisk
	ID             field.Uint64
	UserID         field.Uint64
	Operation      field.String
	IdempotencyKey field.String
	RequestHash    field.Bytes
	OrderID        field.Uint64
	CreatedAt      field.Time
	UpdatedAt      field.Time

	fieldMap map[string]field.Expr
}

func (i idempotencyKey) Table(newTableName string) *idempotencyKey {
	i.idempotencyKeyDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i idempotencyKey) As(alias string) *idempotencyKey {
	i.idempotencyKeyDo.DO = *(i.idempotencyKeyDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *idempotencyKey) updateTableName(table string) *idempotencyKey {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewUint64(table, "id")
	i.UserID = field.NewUint64(table, "user_id")
	i.Operation = field.NewString(table, "operation")
	i.IdempotencyKey = field.NewString(table, "idempotency_key")
	i.RequestHash = field.NewBytes(table, "request_hash")
	i.OrderID = field.NewUint64(table, "order_id")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *idempotencyKey) WithContext(ctx context.Context) IIdempotencyKeyDo {
	return i.idempotencyKeyDo.WithContext(ctx)
}

func (i idempotencyKey) TableName() string { return i.idempotencyKeyDo.TableName() }

func (i idempotencyKey) Alias() string { return i.idempotencyKeyDo.Alias() }

func (i idempotencyKey) Columns(cols ...field.Expr) gen.Columns {
	return i.idempotencyKeyDo.Columns(cols...)
}

func (i *idempotencyKey) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *idempotencyKey) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 8)
	i.fieldMap["id"] = i.ID
	i.fieldMap["user_id"] = i.UserID
	i.fieldMap["operation"] = i.Operation
	i.fieldMap["idempotency_key"] = i.IdempotencyKey
	i.fieldMap["request_hash"] = i.RequestHash
	i.fieldMap["order_id"] = i.OrderID
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i idempotencyKey) clone(db *gorm.DB) idempotencyKey {
	i.idempotencyKeyDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i idempotencyKey) replaceDB(db *gorm.DB) idempotencyKey {
	i.idempotencyKeyDo.ReplaceDB(db)
	return i
}

type idempotencyKeyDo struct{ gen.DO }

type IIdempotencyKeyDo interface {
	gen.SubQuery
	Debug() IIdempotencyKeyDo
	WithContext(ctx context.Context) IIdempotencyKeyDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IIdempotencyKeyDo
	WriteDB() IIdempotencyKeyDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IIdempotencyKeyDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IIdempotencyKeyDo
	Not(conds ...gen.Condition) IIdempotencyKeyDo
	Or(conds ...gen.Condition) IIdempotencyKeyDo
	Select(conds ...field.Expr) IIdempotencyKeyDo
	Where(conds ...gen.Condition) IIdempotencyKeyDo
	Order(conds ...field.Expr) IIdempotencyKeyDo
	Distinct(cols ...field.Expr) IIdempotencyKeyDo
	Omit(cols ...field.Expr) IIdempotencyKeyDo
	Join(table schema.Tabler, on ...field.Expr) IIdempotencyKeyDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IIdempotencyKeyDo
	RightJoin(table schema.Tabler, on ...field.Expr) IIdempotencyKeyDo
	Group(cols ...field.Expr) IIdempotencyKeyDo
	Having(conds ...gen.Condition) IIdempotencyKeyDo
	Limit(limit int) IIdempotencyKeyDo
	Offset(offset int) IIdempotencyKeyDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IIdempotencyKeyDo
	Unscoped() IIdempotencyKeyDo
	Create(values ...*model.IdempotencyKey) error
	CreateInBatches(values []*model.IdempotencyKey, batchSize int) error
	Save(values ...*model.IdempotencyKey) error
	First() (*model.IdempotencyKey, error)
	Take() (*model.IdempotencyKey, error)
	Last() (*model.IdempotencyKey, error)
	Find() ([]*model.IdempotencyKey, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IdempotencyKey, err error)
	FindInBatches(result *[]*model.IdempotencyKey, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.IdempotencyKey) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IIdempotencyKeyDo
	Assign(attrs ...field.AssignExpr) IIdempotencyKeyDo
	Joins(fields ...field.RelationField) IIdempotencyKeyDo
	Preload(fields ...field.RelationField) IIdempotencyKeyDo
	FirstOrInit() (*model.IdempotencyKey, error)
	FirstOrCreate() (*model.IdempotencyKey, error)
	FindByPage(offset int, limit int) (result []*model.IdempotencyKey, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IIdempotencyKeyDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i idempotencyKeyDo) Debug() IIdempotencyKeyDo {
	return i.withDO(i.DO.Debug())
}

func (i idempotencyKeyDo) WithContext(ctx context.Context) IIdempotencyKeyDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i idempotencyKeyDo) ReadDB() IIdempotencyKeyDo {
	return i.Clauses(dbresolver.Read)
}

func (i idempotencyKeyDo) WriteDB() IIdempotencyKeyDo {
	return i.Clauses(dbresolver.Write)
}

func (i idempotencyKeyDo) Session(config *gorm.Session) IIdempotencyKeyDo {
	return i.withDO(i.DO.Session(config))
}

func (i idempotencyKeyDo) Clauses(conds ...clause.Expression) IIdempotencyKeyDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i idempotencyKeyDo) Returning(value interface{}, columns ...string) IIdempotencyKeyDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i idempotencyKeyDo) Not(conds ...gen.Condition) IIdempotencyKeyDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i idempotencyKeyDo) Or(conds ...gen.Condition) IIdempotencyKeyDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i idempotencyKeyDo) Select(conds ...field.Expr) IIdempotencyKeyDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i idempotencyKeyDo) Where(conds ...gen.Condition) IIdempotencyKeyDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i idempotencyKeyDo) Order(conds ...field.Expr) IIdempotencyKeyDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i idempotencyKeyDo) Distinct(cols ...field.Expr) IIdempotencyKeyDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i idempotencyKeyDo) Omit(cols ...field.Expr) IIdempotencyKeyDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i idempotencyKeyDo) Join(table schema.Tabler, on ...field.Expr) IIdempotencyKeyDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i idempotencyKeyDo) LeftJoin(table schema.Tabler, on ...field.Expr) IIdempotencyKeyDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i idempotencyKeyDo) RightJoin(table schema.Tabler, on ...field.Expr) IIdempotencyKeyDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i idempotencyKeyDo) Group(cols ...field.Expr) IIdempotencyKeyDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i idempotencyKeyDo) Having(conds ...gen.Condition) IIdempotencyKeyDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i idempotencyKeyDo) Limit(limit int) IIdempotencyKeyDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i idempotencyKeyDo) Offset(offset int) IIdempotencyKeyDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i idempotencyKeyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IIdempotencyKeyDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i idempotencyKeyDo) Unscoped() IIdempotencyKeyDo {
	return i.withDO(i.DO.Unscoped())
}

func (i idempotencyKeyDo) Create(values ...*model.IdempotencyKey) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i idempotencyKeyDo) CreateInBatches(values []*model.IdempotencyKey, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i idempotencyKeyDo) Save(values ...*model.IdempotencyKey) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i idempotencyKeyDo) First() (*model.IdempotencyKey, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.IdempotencyKey), nil
	}
}

func (i idempotencyKeyDo) Take() (*model.IdempotencyKey, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.IdempotencyKey), nil
	}
}

func (i idempotencyKeyDo) Last() (*model.IdempotencyKey, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.IdempotencyKey), nil
	}
}

func (i idempotencyKeyDo) Find() ([]*model.IdempotencyKey, error) {
	result, err := i.DO.Find()
	return result.([]*model.IdempotencyKey), err
}

func (i idempotencyKeyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.IdempotencyKey, err error) {
	buf := make([]*model.IdempotencyKey, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i idempotencyKeyDo) FindInBatches(result *[]*model.IdempotencyKey, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i idempotencyKeyDo) Attrs(attrs ...field.AssignExpr) IIdempotencyKeyDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i idempotencyKeyDo) Assign(attrs ...field.AssignExpr) IIdempotencyKeyDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i idempotencyKeyDo) Joins(fields ...field.RelationField) IIdempotencyKeyDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i idempotencyKeyDo) Preload(fields ...field.RelationField) IIdempotencyKeyDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i idempotencyKeyDo) FirstOrInit() (*model.IdempotencyKey, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.IdempotencyKey), nil
	}
}

func (i idempotencyKeyDo) FirstOrCreate() (*model.IdempotencyKey, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.IdempotencyKey), nil
	}
}

func (i idempotencyKeyDo) FindByPage(offset int, limit int) (result []*model.IdempotencyKey, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i idempotencyKeyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i idempotencyKeyDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i idempotencyKeyDo) Delete(models ...*model.IdempotencyKey) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *idempotencyKeyDo) withDO(do gen.Dao) *idempotencyKeyDo {
	i.DO = *do.(*gen.DO)
	return i
}
