// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"clean-arch-gin/mysqlstore/model"
)

func newStockAdjustment(db *gorm.DB, opts ...gen.DOOption) stockAdjustment {
	_stockAdjustment := stockAdjustment{}

	_stockAdjustment.stockAdjustmentDo.UseDB(db, opts...)
	_stockAdjustment.stockAdjustmentDo.UseModel(&model.StockAdjustment{})

	tableName := _stockAdjustment.stockAdjustmentDo.TableName()
	_stockAdjustment.ALL = field.NewAsterisk(tableName)
	_stockAdjustment.ID = field.NewUint64(tableName, "id")
	_stockAdjustment.ProductID = field.NewUint64(tableName, "product_id")
	_stockAdjustment.Delta = field.NewInt32(tableName, "delta")
	_stockAdjustment.StockAfter = field.NewUint32(tableName, "stock_after")
	_stockAdjustment.Reason = field.NewString(tableName, "reason")
	_stockAdjustment.ActorUserID = field.NewUint64(tableName, "actor_user_id")
	_stockAdjustment.OrderID = field.NewUint64(tableName, "order_id")
	_stockAdjustment.CreatedAt = field.NewTime(tableName, "created_at")

	_stockAdjustment.fillFieldMap()

	return _stockAdjustment
}

type stockAdjustment struct {
	stockAdjustmentDo stockAdjustmentDo

	ALL         field.Asterisk
	ID          field.Uint64
	ProductID   field.Uint64
	Delta       field.Int32
	StockAfter  field.Uint32
	Reason      field.String
	ActorUserID field.Uint64
	OrderID     field.Uint64
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (s stockAdjustment) Table(newTableName string) *stockAdjustment {
	s.stockAdjustmentDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s stockAdjustment) As(alias string) *stockAdjustment {
	s.stockAdjustmentDo.DO = *(s.stockAdjustmentDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *stockAdjustment) updateTableName(table string) *stockAdjustment {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewUint64(table, "id")
	s.ProductID = field.NewUint64(table, "product_id")
	s.Delta = field.NewInt32(table, "delta")
	s.StockAfter = field.NewUint32(table, "stock_after")
	s.Reason = field.NewString(table, "reason")
	s.ActorUserID = field.NewUint64(table, "actor_user_id")
	s.OrderID = field.NewUint64(table, "order_id")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *stockAdjustment) WithContext(ctx context.Context) IStockAdjustmentDo {
	return s.stockAdjustmentDo.WithContext(ctx)
}

func (s stockAdjustment) TableName() string { return s.stockAdjustmentDo.TableName() }

func (s stockAdjustment) Alias() string { return s.stockAdjustmentDo.Alias() }

func (s stockAdjustment) Columns(cols ...field.Expr) gen.Columns {
	return s.stockAdjustmentDo.Columns(cols...)
}

func (s *stockAdjustment) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *stockAdjustment) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["product_id"] = s.ProductID
	s.fieldMap["delta"] = s.Delta
	s.fieldMap["stock_after"] = s.StockAfter
	s.fieldMap["reason"] = s.Reason
	s.fieldMap["actor_user_id"] = s.ActorUserID
	s.fieldMap["order_id"] = s.OrderID
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s stockAdjustment) clone(db *gorm.DB) stockAdjustment {
	s.stockAdjustmentDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s stockAdjustment) replaceDB(db *gorm.DB) stockAdjustment {
	s.stockAdjustmentDo.ReplaceDB(db)
	return s
}

type stockAdjustmentDo struct{ gen.DO }

type IStockAdjustmentDo interface {
	gen.SubQuery
	Debug() IStockAdjustmentDo
	WithContext(ctx context.Context) IStockAdjustmentDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IStockAdjustmentDo
	WriteDB() IStockAdjustmentDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IStockAdjustmentDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IStockAdjustmentDo
	Not(conds ...gen.Condition) IStockAdjustmentDo
	Or(conds ...gen.Condition) IStockAdjustmentDo
	Select(conds ...field.Expr) IStockAdjustmentDo
	Where(conds ...gen.Condition) IStockAdjustmentDo
	Order(conds ...field.Expr) IStockAdjustmentDo
	Distinct(cols ...field.Expr) IStockAdjustmentDo
	Omit(cols ...field.Expr) IStockAdjustmentDo
	Join(table schema.Tabler, on ...field.Expr) IStockAdjustmentDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IStockAdjustmentDo
	RightJoin(table schema.Tabler, on ...field.Expr) IStockAdjustmentDo
	Group(cols ...field.Expr) IStockAdjustmentDo
	Having(conds ...gen.Condition) IStockAdjustmentDo
	Limit(limit int) IStockAdjustmentDo
	Offset(offset int) IStockAdjustmentDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IStockAdjustmentDo
	Unscoped() IStockAdjustmentDo
	Create(values ...*model.StockAdjustment) error
	CreateInBatches(values []*model.StockAdjustment, batchSize int) error
	Save(values ...*model.StockAdjustment) error
	First() (*model.StockAdjustment, error)
	Take() (*model.StockAdjustment, error)
	Last() (*model.StockAdjustment, error)
	Find() ([]*model.StockAdjustment, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StockAdjustment, err error)
	FindInBatches(result *[]*model.StockAdjustment, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.StockAdjustment) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IStockAdjustmentDo
	Assign(attrs ...field.AssignExpr) IStockAdjustmentDo
	Joins(fields ...field.RelationField) IStockAdjustmentDo
	Preload(fields ...field.RelationField) IStockAdjustmentDo
	FirstOrInit() (*model.StockAdjustment, error)
	FirstOrCreate() (*model.StockAdjustment, error)
	FindByPage(offset int, limit int) (result []*model.StockAdjustment, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IStockAdjustmentDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s stockAdjustmentDo) Debug() IStockAdjustmentDo {
	return s.withDO(s.DO.Debug())
}

func (s stockAdjustmentDo) WithContext(ctx context.Context) IStockAdjustmentDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s stockAdjustmentDo) ReadDB() IStockAdjustmentDo {
	return s.Clauses(dbresolver.Read)
}

func (s stockAdjustmentDo) WriteDB() IStockAdjustmentDo {
	return s.Clauses(dbresolver.Write)
}

func (s stockAdjustmentDo) Session(config *gorm.Session) IStockAdjustmentDo {
	return s.withDO(s.DO.Session(config))
}

func (s stockAdjustmentDo) Clauses(conds ...clause.Expression) IStockAdjustmentDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s stockAdjustmentDo) Returning(value interface{}, columns ...string) IStockAdjustmentDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s stockAdjustmentDo) Not(conds ...gen.Condition) IStockAdjustmentDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s stockAdjustmentDo) Or(conds ...gen.Condition) IStockAdjustmentDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s stockAdjustmentDo) Select(conds ...field.Expr) IStockAdjustmentDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s stockAdjustmentDo) Where(conds ...gen.Condition) IStockAdjustmentDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s stockAdjustmentDo) Order(conds ...field.Expr) IStockAdjustmentDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s stockAdjustmentDo) Distinct(cols ...field.Expr) IStockAdjustmentDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s stockAdjustmentDo) Omit(cols ...field.Expr) IStockAdjustmentDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s stockAdjustmentDo) Join(table schema.Tabler, on ...field.Expr) IStockAdjustmentDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s stockAdjustmentDo) LeftJoin(table schema.Tabler, on ...field.Expr) IStockAdjustmentDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s stockAdjustmentDo) RightJoin(table schema.Tabler, on ...field.Expr) IStockAdjustmentDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s stockAdjustmentDo) Group(cols ...field.Expr) IStockAdjustmentDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s stockAdjustmentDo) Having(conds ...gen.Condition) IStockAdjustmentDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s stockAdjustmentDo) Limit(limit int) IStockAdjustmentDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s stockAdjustmentDo) Offset(offset int) IStockAdjustmentDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s stockAdjustmentDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IStockAdjustmentDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s stockAdjustmentDo) Unscoped() IStockAdjustmentDo {
	return s.withDO(s.DO.Unscoped())
}

func (s stockAdjustmentDo) Create(values ...*model.StockAdjustment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s stockAdjustmentDo) CreateInBatches(values []*model.StockAdjustment, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s stockAdjustmentDo) Save(values ...*model.StockAdjustment) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s stockAdjustmentDo) First() (*model.StockAdjustment, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockAdjustment), nil
	}
}

func (s stockAdjustmentDo) Take() (*model.StockAdjustment, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockAdjustment), nil
	}
}

func (s stockAdjustmentDo) Last() (*model.StockAdjustment, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockAdjustment), nil
	}
}

func (s stockAdjustmentDo) Find() ([]*model.StockAdjustment, error) {
	result, err := s.DO.Find()
	return result.([]*model.StockAdjustment), err
}

func (s stockAdjustmentDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.StockAdjustment, err error) {
	buf := make([]*model.StockAdjustment, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s stockAdjustmentDo) FindInBatches(result *[]*model.StockAdjustment, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s stockAdjustmentDo) Attrs(attrs ...field.AssignExpr) IStockAdjustmentDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s stockAdjustmentDo) Assign(attrs ...field.AssignExpr) IStockAdjustmentDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s stockAdjustmentDo) Joins(fields ...field.RelationField) IStockAdjustmentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s stockAdjustmentDo) Preload(fields ...field.RelationField) IStockAdjustmentDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s stockAdjustmentDo) FirstOrInit() (*model.StockAdjustment, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockAdjustment), nil
	}
}

func (s stockAdjustmentDo) FirstOrCreate() (*model.StockAdjustment, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.StockAdjustment), nil
	}
}

func (s stockAdjustmentDo) FindByPage(offset int, limit int) (result []*model.StockAdjustment, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s stockAdjustmentDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s stockAdjustmentDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s stockAdjustmentDo) Delete(models ...*model.StockAdjustment) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *stockAdjustmentDo) withDO(do gen.Dao) *stockAdjustmentDo {
	s.DO = *do.(*gen.DO)
	return s
}
