// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"log/slog"
)

// Injectors from wire.go:

func initializeAdminDependencies(logger *slog.Logger) (adminDependencies, error) {
	mainMigrationRunner := provideMigrationRunner()
	mainAdminBootstrapper := provideBootstrapper(logger)
	mainPasswordReader := providePasswordReader()
	mainAdminDependencies := provideAdminDependencies(mainMigrationRunner, mainAdminBootstrapper, mainPasswordReader)
	return mainAdminDependencies, nil
}
