// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"clean-arch-gin/config"
	"clean-arch-gin/mysqlstore"
	"clean-arch-gin/order"
	"clean-arch-gin/product"
	"clean-arch-gin/reporting"
	"clean-arch-gin/user"
	"context"
	"log/slog"
	"net"
)

// Injectors from wire.go:

func buildRuntime(ctx context.Context, cfg config.Config, logger *slog.Logger, listener net.Listener, db databaseResource) (serverRuntime, error) {
	db2 := gormDB(db)
	userStore, err := mysqlstore.NewUserStore(db2)
	if err != nil {
		return serverRuntime{}, err
	}
	sessionStore, err := mysqlstore.NewSessionStore(db2)
	if err != nil {
		return serverRuntime{}, err
	}
	passwordManager, err := providePasswordManager(cfg)
	if err != nil {
		return serverRuntime{}, err
	}
	jwt, err := provideJWT(cfg)
	if err != nil {
		return serverRuntime{}, err
	}
	refreshGenerator, err := provideRefreshGenerator()
	if err != nil {
		return serverRuntime{}, err
	}
	randomIDGenerator, err := provideIDGenerator()
	if err != nil {
		return serverRuntime{}, err
	}
	clock := provideUserClock()
	duration := provideRefreshTTL(cfg)
	authService, err := user.NewAuthService(userStore, sessionStore, passwordManager, jwt, refreshGenerator, randomIDGenerator, clock, duration)
	if err != nil {
		return serverRuntime{}, err
	}
	service, err := user.NewService(userStore, passwordManager, clock)
	if err != nil {
		return serverRuntime{}, err
	}
	productStore, err := mysqlstore.NewProductStore(db2)
	if err != nil {
		return serverRuntime{}, err
	}
	productClock := provideProductClock()
	productService, err := product.NewService(productStore, productClock)
	if err != nil {
		return serverRuntime{}, err
	}
	orderStore, err := mysqlstore.NewOrderStore(db2)
	if err != nil {
		return serverRuntime{}, err
	}
	orderClock := provideOrderClock()
	numberGenerator := provideNumberGenerator()
	orderService, err := order.NewService(orderStore, orderStore, orderClock, numberGenerator)
	if err != nil {
		return serverRuntime{}, err
	}
	reportingStore, err := mysqlstore.NewReportingStore(db2)
	if err != nil {
		return serverRuntime{}, err
	}
	reportingService, err := reporting.NewService(reportingStore)
	if err != nil {
		return serverRuntime{}, err
	}
	handler, err := provideRouter(ctx, cfg, logger, db, authService, service, productService, orderService, reportingService)
	if err != nil {
		return serverRuntime{}, err
	}
	mainServerRuntime := provideServerRuntime(cfg, handler, listener, db)
	return mainServerRuntime, nil
}
